# ref. https://github.com/bitnami/bitnami-docker-mysql/blob/master/docker-compose.yml

# usage: docker-compose up -d
#      : mysql -h 127.0.0.1 -u root

version: '2.1'

services:
  mysql:
    image: docker.io/bitnami/mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mysql_data:
    driver: local
